MathMixer/MathMixer/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', lambda request: redirect('users:home', permanent=True)),
    path('users/', include('users.urls', namespace='users')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('main/', include('main.urls', namespace='main'))
]

MathMixer/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('trainers/equation/', views.trainersEquation, name='trainersE'),
    path('trainers/numbers/', views.trainersNumbers, name='trainersN'),
    path('trainers/unequal/', views.trainersUnequal, name='trainersU'),
    path('equation1/select_difficulty/', views.select_difficulty, name='select_difficulty'),
    path('equation1/play_game/', views.play_game, name='play_game'),
]

MathMixer/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import LoginUsersView, ProfileView, trainers_redirect, edit_profile, register, home

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('home/', home, name='home'),
    path('login/', LoginUsersView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('trainers_redirect/', trainers_redirect, name='trainers_redirect'),
    path('edit_profile/', edit_profile, name='edit_profile')
]

MathMixer/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='avatars/', null=True, blank=True, verbose_name='Аватар')


    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

MathMixer/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm

from .models import User


class LoginUserForm(AuthenticationForm):

    username = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': 'Введите имя',
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            'class': 'form-control',
            'placeholder': 'Введите пароль',
        })
    )
    class Meta:
        model = User
        fields = ['username', 'password']

class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите ваше имя',
        })
    )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите ваш email',
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль',
        })
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Повторите пароль',
        })
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password2']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают!')
        return cd['password']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Такой E-mail уже существует!')
        return email

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    username = forms.CharField()
    email = forms.CharField()

MathMixer/users/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, login
from django.urls import reverse
from django.views.generic import TemplateView
from .forms import LoginUserForm, RegisterUserForm
from django.contrib.auth.views import LoginView
def register(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            print("Form is valid")
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.avatar = 'static/avatars/default_avatar.png'
            user.save()
            login(request, user)
            return redirect('users:home')
        else:
            print(form.errors)
            print("Form is not valid")
    else:
        form = RegisterUserForm()
    return render(request, 'register.html', {'form': form})

def home(request):
    return render(request, 'home.html')

class LoginUsersView(LoginView):
    form_class = LoginUserForm
    template_name = 'login.html'

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['date_joined'] = user.date_joined
        return context
def trainers_redirect(request):
    if request.user.is_authenticated:
        return redirect(reverse('main:trainersN'))
    else:
        return redirect(reverse('users:login'))
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профайл успешно обновлен")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
    return render(request, 'edit_profile.html')

MathMixer/users/templates/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Профиль пользователя</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body style="background-color: rgba(255, 255, 255, 0.767);">
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-expand-lg navbar-dark d-lg-none w-100" style="background-color: rgb(56, 0, 94);">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">{{user.username}}</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'users:home' %}">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'users:profile' %}">Мой профиль</a>
                            </li>
                            <li class="nav-item">
                                <span class="nav-link dropdown-btn text-light">Тренажеры <span style="font-size: 12px;">▼</span></span>
                                <div class="dropdown-container">
                                    <a class="nav-link" href="{% url 'main:trainersN' %}">Числовой пример</a>
                                    <a class="nav-link" href="{% url 'main:trainersE' %}">Уравнение</a>
                                    <a class="nav-link" href="{% url 'main:trainersU' %}">Неравенство</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:logout' %}">Выйти из аккаунта</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-none d-lg-block sidebar" style="position: fixed;">
                <div class="position-sticky pt-3">
                    <div class="text-center mb-4">
                        <img src="https://via.placeholder.com/100" class="rounded-circle" alt="Профиль">
                        <h4 class="text-light mt-2">{{user.username}}</h4>
                    </div>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active text-light" aria-current="page" href="{% url 'users:home' %}">
                                Главная
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" aria-current="page" href="{% url 'users:profile' %}">
                                Мой профиль
                            </a>
                        </li>
                        <li class="nav-item">
                            <span class="nav-link dropdown-btn text-light">Тренажеры <span style="font-size: 12px;">▼</span></span>
                            <div class="dropdown-container">
                                <a class="nav-link text-light" href="{% url 'main:trainersN' %}">Числовой пример</a>
                                <a class="nav-link text-light" href="{% url 'main:trainersE' %}">Уравнение</a>
                                <a class="nav-link text-light" href="{% url 'main:trainersU' %}">Неравенство</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'users:logout' %}">
                                Выйти из аккаунта
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <section class="ms-sm-auto col-lg-10 px-md-4">
                <div class="container py-5">
                    <div class="d-flex justify-content-center flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                        <h3>Редактирование профиля</h3>
                    </div>

                    <div class="row mt-5">
                        <div class="col-lg-6">
                            <div class="card mb-4">
                                <div class="card-body text-center">
                                    <div class="profile-img">
                                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar" class="rounded-circle img-fluid" id="edit_img">
                                    </div>
                                    <h5 class="my-3">{{user.username}}</h5>
                                    <p class="text-muted mb-1">{{user.email}}</p>
                                    <div class="d-flex justify-content-center mb-2">
                                        <label for="file-input" class="btn btn-primary">Изменить аватарку</label>
                                        <input id="file-input" type="file" style="display: none;">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <form>
                                <div class="mb-3">
                                    <label for="username" class="form-label">Имя пользователя</label>
                                    <input type="text" class="form-control" id="username" placeholder="Введите новое имя пользователя">
                                </div>
                                <div class="mb-3">
                                    <label for="email" class="form-label">Email</label>
                                    <input type="email" class="form-control" id="email" placeholder="Введите новый email">
                                </div>
                                <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        // Обработчик события для изменения аватарки
        document.getElementById('file-input').addEventListener('change', function(event) {
            var file = this.files[0];
            if (file) {
                var reader = new FileReader();
                reader.onload = function(event) {
                    document.getElementById('edit_img').src = event.target.result;
                }
                reader.readAsDataURL(file);
            }
        });
    </script>
</body>

MathMixer/users/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Вход</title>
</head>
<body>
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-6">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <h2 class="text-center mb-5">Вход</h2>
                            <form action="{% url 'users:login' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group mb-4">
                                    <label for="{{ form.username.id_for_label }}" class="mb-2">Имя пользователя</label>
                                    {{ form.username }}
                                </div>
                                <div class="form-group mb-4">
                                    <label for="{{ form.password.id_for_label }}" class="mb-2">Пароль</label>
                                    {{ form.password }}
                                </div>
                                <div class="form-check mb-4 p-0 d-flex justify-content-between">
                                    <label class="form-check-label" for="terms">
                                        Еще не зарегистрированы? <br><a href="{% url 'users:register' %}">Регистрация</a>
                                    </label>
                                    <label class="form-check-label" for="terms">
                                        <a href="#!">Забыли пароль?</a>
                                    </label>
                                </div>
                                <div class="d-flex justify-content-center">
                                    <button type="submit" class="btn btn-primary px-5 py-2">Войти</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 d-none d-lg-block">
                    <img src="{% static 'image/reg-bg.png' %}" class="img-fluid" alt="image-bg" width="600" height="600">
                </div>
            </div>
        </div>
    </section>
</body>
</html>

MathMixer/users/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Профиль пользователя</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src=" {% static 'js/chart.js' %}"></script>
</head>
<body style="background-color: rgba(255, 255, 255, 0.767);">
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-expand-lg navbar-dark d-lg-none w-100" style="background-color: rgb(56, 0, 94);">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">{{user.username}}</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'users:home' %}">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="#">Мой профиль</a>
                            </li>
                            <li class="nav-item">
                                <span class="nav-link dropdown-btn text-light">Тренажеры <span style="font-size: 12px;">▼</span></span>
                                <div class="dropdown-container">
                                    <a class="nav-link" href="{% url 'main:trainersN' %}">Числовой пример</a>
                                    <a class="nav-link" href="{% url 'main:trainersE' %}">Уравнение</a>
                                    <a class="nav-link" href="{% url 'main:trainersU' %}">Неравенство</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Выйти из аккаунта</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-none d-lg-block sidebar" style="position: fixed;">
                <div class="position-sticky pt-3">
                    <div class="profile-img">
                        <img src="{% static 'avatars/default_avatar.jpg' %}" class="rounded-circle img-fluid" alt="Профиль">
                        {% if user.image %}
                            <img src="{{ user.image.url }}" alt="Аватар пользователя" class="img-fluid rounded-circle" style="max-width: 150px;">
                        {% else %}
                            <img src="{% static 'image/default_avatar' %}" alt="Аватар пользователя" class="img-fluid rounded-circle" tyle="max-width: 150px;">
                        {% endif %}
                    </div>
                    <div class="text-center mb-4">
                        <h4 class="text-light mt-2">{{ user.username }}</h4>
                    </div>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active text-light" aria-current="page" href="{% url 'users:home' %}">
                                Главная
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" aria-current="page" href="#">
                                Мой профиль
                            </a>
                        </li>
                        <li class="nav-item">
                            <span class="nav-link dropdown-btn text-light">Тренажеры <span style="font-size: 12px;">▼</span></span>
                            <div class="dropdown-container">
                                <a class="nav-link text-light" href="{% url 'main:trainersN' %}">Числовой пример</a>
                                <a class="nav-link text-light" href="{% url 'main:trainersE' %}">Уравнение</a>
                                <a class="nav-link text-light" href="{% url 'main:trainersU' %}">Неравенство</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'users:logout' %}">
                                Выйти из аккаунта
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <section class="ms-sm-auto col-lg-10 px-md-4">
                <div class="container py-5">
                    <div class="d-flex justify-content-center flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                        <h3>Мой профиль</h3>
                    </div>

                    <div class="row mt-5">
                        <div class="col-lg-5">
                            <div class="card mb-4">
                                <div class="card-body text-center">
                                    <div class="profile-img">
                                        <img src="{% static 'avatars/default_avatar.jpg' %}" alt="avatar" class="rounded-circle img-fluid">
                                    </div>
                                    <h5 class="my-3">{{ user.username }}</h5>
                                    <p class="text-muted mb-1">Статус: Активен</p>
                                    <div class="d-flex justify-content-center mb-2">
                                        <a type="button" class="btn btn-primary" href="{% url 'users:edit_profile' %}">Редактировать профиль</a>
                                    </div>
                                </div>
                            </div>

                            <div class="account-info card mb-4">
                                <h4 class="mb-4">Данные аккаунта</h4>
                                <div class="row mb-2">
                                    <div class="col-sm-4">
                                        <p class="info-title">Дата регистрации</p>
                                    </div>
                                    <div class="col-sm-8">
                                        <p class="text-muted">{{date_joined}}</p>
                                    </div>
                                </div>
                                <hr>
                                <div class="row mb-1">
                                    <div class="col-sm-4">
                                        <p class="info-title">Место в топе</p>
                                    </div>
                                    <div class="col-sm-8">
                                        <p class="text-muted">1</p>
                                    </div>
                                </div>
                                <hr>
                                <div class="row mb-2">
                                    <div class="col-sm-4">
                                        <p class="info-title">Кол-во тренировок</p>
                                    </div>
                                    <div class="col-sm-8">
                                        <p class="text-muted">2</p>
                                    </div>
                                </div>
                                <hr>
                                <div class="row mb-2">
                                    <div class="col-sm-4">
                                        <p class="info-title">Любимый тренажер</p>
                                    </div>
                                    <div class="col-sm-8">
                                        <p class="text-muted">Мемори</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-7">
                            <div class="card mb-4">
                                <div class="card-body">
                                    <h4 class="mb-4">Статистика</h4>
                                    <canvas id="accuracyChart"></canvas>
                                </div>
                            </div>

                            <div class="card mb-4">
                                <div class="card-body">
                                    <div class="row mb-2">
                                        <div class="col-sm-3">
                                            <p class="info-title">Имя</p>
                                        </div>
                                        <div class="col-sm-9">
                                            <p class="text-muted">{{user.username}}</p>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row mb-2">
                                        <div class="col-sm-3">
                                            <p class="info-title">Email</p>
                                        </div>
                                        <div class="col-sm-9">
                                            <p class="text-muted">{{user.email}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

MathMixer/users/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Регистрация</title>
</head>
<body>
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-6">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <h2 class="text-center mb-5">Регистрация</h2>
                            <form action="{% url 'users:register'%}" method="POST">
                                {% csrf_token %}
                                <div class="form-group mb-4">
                                    <label for="{{ form.username.id_for_label }}" class="mb-2">Ваше имя</label>
                                    {{ form.username }}
                                     <div class="text-danger">{{ form.username.errors }}</div>
                                </div>
                                <div class="form-group mb-4">
                                    <label for="{{ form.email.id_for_label }}" class="mb-2">Ваш Email</label>
                                    {{ form.email }}
                                     <div class="text-danger">{{ form.email.errors }}</div>
                                </div>
                                <div class="form-group mb-4">
                                    <label for="{{ form.password.id_for_label }}" class="mb-2">Пароль</label>
                                    {{ form.password}}
                                     <div class="text-danger">{{ form.password.errors }}</div>
                                </div>
                                <div class="form-group mb-4">
                                    <label for="{{ form.password2.id_for_label }}" class="mb-2">Повторите пароль</label>
                                    {{ form.password2 }}
                                     <div class="text-danger">{{ form.password2.errors }}</div>
                                </div>
                                <div class="d-flex justify-content-center">
                                    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                                </div>
                            </form>
                            {% if form.non_field_errors %}
                            <div class="text-danger">
                                <ul>
                                    {% for error in form.non_field_errors %}
                                     <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                             </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 d-none d-lg-block">
                    <img src="{% static 'image/reg-bg.png' %}" class="img-fluid" alt="image-bg" width="600" height="600">
                </div>
            </div>
        </div>
    </section>
</body>
</html>